### PR TITLE
.NET 6 Update

### PR DESCRIPTION
**Pull request by Christian-Oleson**

### CODE REVIEW

**Comment by zo0o0ot** [comment]
Determining projects to restore...
/usr/share/dotnet/sdk/5.0.403/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(141,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 6.0.  Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0. [/workspaces/prospect-scraper-mddb-2022/prospect-scraper-mddb-2022.csproj]
Done: 1.

**Comment by Christian-Oleson** [comment]
> Determining projects to restore... /usr/share/dotnet/sdk/5.0.403/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(141,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 6.0. Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0. [/workspaces/prospect-scraper-mddb-2022/prospect-scraper-mddb-2022.csproj] Done: 1.

Is this locally for you?

**Comment by zo0o0ot** [comment]
> > Determining projects to restore... /usr/share/dotnet/sdk/5.0.403/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(141,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 6.0. Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0. [/workspaces/prospect-scraper-mddb-2022/prospect-scraper-mddb-2022.csproj] Done: 1.
> 
> Is this locally for you?

This is what happens when I try to do a dontnet restore from inside the Codespaces instance.  It could be that we also need to update the configuration of the container to ensure that the runtime is present after the upgrade to .NET 6

That might be here:

https://github.com/Leagify/prospect-scraper-mddb-2022/blob/6ede9e9bfa125066c1f310d95a9de794b04759cf/.devcontainer/Dockerfile#L3-L5

https://github.com/Leagify/prospect-scraper-mddb-2022/blob/6ede9e9bfa125066c1f310d95a9de794b04759cf/.devcontainer/devcontainer.json#L6-L13

**Comment by Christian-Oleson** [comment]
> > > Determining projects to restore... /usr/share/dotnet/sdk/5.0.403/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(141,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 6.0. Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0. [/workspaces/prospect-scraper-mddb-2022/prospect-scraper-mddb-2022.csproj] Done: 1.
> > 
> > 
> > Is this locally for you?
> 
> This is what happens when I try to do a dontnet restore from inside the Codespaces instance. It could be that we also need to update the configuration of the container to ensure that the runtime is present after the upgrade to .NET 6
> 
> That might be here:
> 
> https://github.com/Leagify/prospect-scraper-mddb-2022/blob/6ede9e9bfa125066c1f310d95a9de794b04759cf/.devcontainer/Dockerfile#L3-L5
> 
> https://github.com/Leagify/prospect-scraper-mddb-2022/blob/6ede9e9bfa125066c1f310d95a9de794b04759cf/.devcontainer/devcontainer.json#L6-L13

K, I wasn't aware of that. Perhaps try now?

**Pull request closed without merging**
